"use client";

import { DynamicFormComponent } from "../components/DynamicForm/DynamicForm";
import {
  GetRepositoryListDocument,
  GetRepositoryListQueryVariables,
} from "../graphql/types";
import { useRouter } from "next/navigation";
import { Routes } from "../config/Routes";


const RepoPage = () => {
  const router = useRouter();
  const onSubmit = (values: GetRepositoryListQueryVariables) => {
    router.push(Routes.getRepoListRoute(values.login, values.limit));
  };

  return (
    <div className={"page"}>
      <div className={"main"}>
        <h4 className="mb-4">Bellow form is rendered dynamically using a graphql query.<br/> Also the validation schema is autogenerated using yup.</h4>
        <div>
        <DynamicFormComponent<GetRepositoryListQueryVariables>
          query={GetRepositoryListDocument}
          onSubmit={onSubmit}
        />
        </div>
      </div>
    </div>
  );
};

export default RepoPage;
