import Image from "next/image";
import { Routes } from "./config/Routes";
import styles from "./page.module.css";

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <ol>
          <li>
            The project is created to illustrate usage of graphql with next js and typescript.
          </li>
          <li>In next page you will see a form which is dynamically rendered using graphql autogenerated query hook.</li>
        </ol>

        <div className={styles.ctas}>
          <a
            className={styles.primary}
            href={Routes.getRepoRoute()}
          >
            <Image
              className={styles.logo}
              src="/vercel.svg"
              alt="Vercel logomark"
              width={20}
              height={20}
            />
            Get Started!
          </a>
        </div>
      </main>
    </div>
  );
}
